"""init

Revision ID: b466a8ba905d
Revises: 
Create Date: 2022-09-17 07:48:47.474424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b466a8ba905d'
down_revision = None
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum_postgres = postgresql.ENUM('started', 'finished', 'preparing', 'cancelled', name='status_choice', create_type=False)
    status_enum = sa.Enum('started', 'finished', 'preparing', 'cancelled', name='status_choice')
    status_enum.with_variant(status_enum_postgres, 'postgresql')
    op.create_table('shift',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', status_enum, nullable=False),
    sa.Column('started_at', sa.DATE(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('finished_at', sa.DATE(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift')
    status_enum_postgres = postgresql.ENUM('started', 'finished', 'preparing', 'cancelled', name='status_choice', create_type=False)
    status_enum = sa.Enum('started', 'finished', 'preparing', 'cancelled', name='status_choice')
    status_enum.with_variant(status_enum_postgres, 'postgresql')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
