"""request_shift_id_nullable_true

Revision ID: 40042a774fa2
Revises: 0c58d989449f
Create Date: 2022-10-04 22:14:59.057958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40042a774fa2'
down_revision = '0c58d989449f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'shift_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'shift_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
