"""Report.report_url nullable

Revision ID: 92687721aed3
Revises: 0243cc563a4c
Create Date: 2022-12-30 21:18:23.922652

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '92687721aed3'
down_revision = '0243cc563a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_url',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_url',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    # ### end Alembic commands ###
