"""add_member_model

Revision ID: c919d5a7addc
Revises: 1d0b63b24b19
Create Date: 2022-11-28 22:47:57.441244

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c919d5a7addc'
down_revision = '1d0b63b24b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Enum('active', 'excluded', name='member_status'), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('shift_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('numbers_lombaryers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shift_id', name='_user_shift_uc')
    )
    op.add_column('user_tasks', sa.Column('member_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('_user_task_uc', 'user_tasks', type_='unique')
    op.create_unique_constraint('_member_task_uc', 'user_tasks', ['shift_id', 'task_date', 'member_id'])
    op.create_foreign_key('user_tasks_member_id_fkey', 'user_tasks', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_constraint('_member_task_uc', 'user_tasks', type_='unique')
    op.create_unique_constraint('_user_task_uc', 'user_tasks', ['user_id', 'shift_id', 'task_date'])
    op.drop_column('user_tasks', 'member_id')
    op.drop_table('members')
    # ### end Alembic commands ###
