"""change_model_healthcheckresponse

Revision ID: bd705c65703d
Revises: 07632ea625a5
Create Date: 2022-11-23 17:52:13.464062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd705c65703d'
down_revision = '07632ea625a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
