"""1

Revision ID: 590ee52d6017
Revises: 40042a774fa2
Create Date: 2022-10-15 18:43:09.745435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590ee52d6017'
down_revision = '40042a774fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
