"""request_shift_id_nullable_true

Revision ID: 98d6d4cfccb2
Revises: d37fa6413c00
Create Date: 2022-09-21 00:28:03.910154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98d6d4cfccb2'
down_revision = 'd37fa6413c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'shift_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.create_index(op.f('ix_shifts_finished_at'), 'shifts', ['finished_at'], unique=False)
    op.create_index(op.f('ix_shifts_started_at'), 'shifts', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_started_at'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_finished_at'), table_name='shifts')
    op.alter_column('requests', 'shift_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
