"""Combine photo and usertask

Revision ID: 1d0b63b24b19
Revises: 07632ea625a5
Create Date: 2022-11-20 23:49:32.045750

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d0b63b24b19'
down_revision = '07632ea625a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('report_url', sa.String(length=4096), nullable=True))
    op.add_column('user_tasks', sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_tasks', sa.Column('is_repeated', sa.Boolean(), nullable=True))
    op.execute("UPDATE user_tasks SET is_repeated='FALSE', report_url=''")
    op.execute("UPDATE user_tasks AS ut SET report_url=p.url, uploaded_at=p.created_at FROM photos AS p WHERE ut.photo_id=p.id")
    op.alter_column('user_tasks', 'report_url', nullable=False)
    op.alter_column('user_tasks', 'is_repeated', nullable=False)
    op.create_unique_constraint('user_tasks_report_url_key', 'user_tasks', ['report_url'])
    op.drop_constraint('user_tasks_photo_id_fkey', 'user_tasks', type_='foreignkey')
    op.drop_column('user_tasks', 'photo_id')
    op.drop_table('photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='photos_pkey'),
    sa.UniqueConstraint('url', name='photos_url_key')
    )
    op.execute("INSERT INTO photos(id, deleted, url, created_at)  SELECT id, FALSE as deleted, report_url AS url, (uploaded_at + TIME '00:00:00') AS created_at FROM user_tasks WHERE uploaded_at IS NOT NULL")
    op.add_column('user_tasks', sa.Column('photo_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_tasks_photo_id_fkey', 'user_tasks', 'photos', ['photo_id'], ['id'])
    op.execute("UPDATE user_tasks SET photo_id=id WHERE id IN(SELECT id FROM photos)")
    op.drop_constraint('user_tasks_report_url_key', 'user_tasks', type_='unique')
    op.drop_column('user_tasks', 'is_repeated')
    op.drop_column('user_tasks', 'uploaded_at')
    op.drop_column('user_tasks', 'report_url')
    # ### end Alembic commands ###
