"""add_lombaryers_fields

Revision ID: fb9db4c9f3f9
Revises: 40042a774fa2
Create Date: 2022-10-14 15:46:00.390347

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fb9db4c9f3f9'
down_revision = '40042a774fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('lombaryers', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('lombaryers_sum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lombaryers_sum')
    op.drop_column('requests', 'lombaryers')
    # ### end Alembic commands ###
