"""Report.report_url not unique

Revision ID: 94eef9c81ed7
Revises: 0243cc563a4c
Create Date: 2022-12-27 23:38:10.127325

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '94eef9c81ed7'
down_revision = '0243cc563a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_tasks_report_url_key', 'reports', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_tasks_report_url_key', 'reports', ['report_url'])
    # ### end Alembic commands ###
