"""change field day_number on day

Revision ID: 92f9c64aaa23
Revises: 40042a774fa2
Create Date: 2022-10-17 04:25:19.062074

"""
from datetime import date

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f9c64aaa23'
down_revision = '40042a774fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('day', sa.DATE(), nullable=False, server_default=str(date.today())))
    op.drop_column('user_tasks', 'day_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_tasks', 'day')
    # ### end Alembic commands ###
