"""shift update started/finished

Revision ID: 0c58d989449f
Revises: d37fa6413c00
Create Date: 2022-10-03 18:38:59.845607

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0c58d989449f'
down_revision = '2c2d12934211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shifts_finished_at'), 'shifts', ['finished_at'], unique=False)
    op.create_index(op.f('ix_shifts_started_at'), 'shifts', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_started_at'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_finished_at'), table_name='shifts')
    # ### end Alembic commands ###
