"""Added status field for User

Revision ID: c4e2d5cec3b4
Revises: 691cdea87322
Create Date: 2022-12-18 18:16:45.308914

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4e2d5cec3b4'
down_revision = '691cdea87322'
branch_labels = None
depends_on = None

STATUS_ENUM = sa.Enum('verified', 'declined', 'pending', name='user_status')
STATUS_ENUM_POSTGRES = postgresql.ENUM('verified', 'declined', 'pending', name='user_status', create_type=False)
STATUS_ENUM.with_variant(STATUS_ENUM_POSTGRES, 'postgresql')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    STATUS_ENUM.create(op.get_bind(), checkfirst=False)
    op.add_column('users', sa.Column('status', STATUS_ENUM, nullable=True))
    op.execute("UPDATE users SET status='pending'")
    op.alter_column('users', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    STATUS_ENUM.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
