"""change_field_day_number_on_day_date

Revision ID: cb7474c51c26
Revises: 40042a774fa2
Create Date: 2022-10-15 17:51:06.191878

"""
from datetime import date

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cb7474c51c26'
down_revision = '40042a774fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('day_date', sa.DATE(), nullable=False, server_default=str(date.today())))
    op.drop_column('user_tasks', 'day_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_tasks', 'day_date')
    # ### end Alembic commands ###
