"""Extend final message length

Revision ID: e2c72f7ee109
Revises: 0ae05a7f87ee
Create Date: 2022-11-16 23:52:44.176177

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e2c72f7ee109'
down_revision = '0ae05a7f87ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'final_message',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=400),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'final_message',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
