"""Add field is_repeated to request model

Revision ID: e0412602dac5
Revises: 0243cc563a4c
Create Date: 2022-12-27 19:09:40.394609

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e0412602dac5'
down_revision = '0243cc563a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('is_repeated', sa.Integer(), nullable=True))
    op.execute("UPDATE requests SET is_repeated = 1")
    op.alter_column('requests', 'is_repeated', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'is_repeated')
    # ### end Alembic commands ###
