"""change_unique_constraint_for_usertask_model

Revision ID: 07632ea625a5
Revises: e2c72f7ee109
Create Date: 2022-11-18 20:53:04.479479

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '07632ea625a5'
down_revision = 'e2c72f7ee109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_task_uc', 'user_tasks', type_='unique')
    op.create_unique_constraint('_user_task_uc', 'user_tasks', ['user_id', 'shift_id', 'task_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_task_uc', 'user_tasks', type_='unique')
    op.create_unique_constraint('_user_task_uc', 'user_tasks', ['user_id', 'shift_id', 'task_id'])
    # ### end Alembic commands ###
