"""Report.report_url nullable

Revision ID: 9d5d33dfbdcf
Revises: e0412602dac5
Create Date: 2022-12-31 00:19:59.166053

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9d5d33dfbdcf'
down_revision = 'e0412602dac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_url',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_url',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    # ### end Alembic commands ###
