"""add_sequence_number_and_tasks_to_shift

Revision ID: 490ffbfbc647
Revises: 1d0b63b24b19
Create Date: 2022-11-30 20:05:19.229180

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '490ffbfbc647'
down_revision = '1d0b63b24b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('sequence_number', sa.Integer(), primary_key=True, autoincrement=True, nullable=True))
    op.add_column('shifts', sa.Column('tasks', sa.JSON(), nullable=True))
    op.execute("UPDATE shifts SET sequence_number=1")
    op.execute("UPDATE shifts SET tasks='{}'")
    op.alter_column('shifts', 'sequence_number', nullable=False)
    op.alter_column('shifts', 'tasks', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'tasks')
    op.drop_column('shifts', 'sequence_number')
    # ### end Alembic commands ###
