"""add_report_status_skipped

Revision ID: 093cd892a57e
Revises: fb0616f8ae8e
Create Date: 2023-02-23 21:17:14.712961

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '093cd892a57e'
down_revision = 'fb0616f8ae8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
