"""add report reviewer info

Revision ID: da30cdde53ef
Revises: 3e856b1ea0c1
Create Date: 2023-03-27 23:54:07.438413

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da30cdde53ef'
down_revision = '3e856b1ea0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('reports', sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'reports', 'administrators', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'reviewed_at')
    op.drop_column('reports', 'updated_by')
    # ### end Alembic commands ###
