"""Add is_archived field to Task model

Revision ID: f6d8ae335094
Revises: bcda11280d4d
Create Date: 2023-04-11 17:23:37.504831

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f6d8ae335094'
down_revision = 'bcda11280d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_archived')
    # ### end Alembic commands ###
