"""server_default to is_superadmin

Revision ID: f3a19d153089
Revises: 7e2638eb39b5
Create Date: 2023-03-28 18:45:41.331607

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f3a19d153089'
down_revision = '7e2638eb39b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
