"""add is_superuser field to admin

Revision ID: 21b7c35b3419
Revises: 3e856b1ea0c1
Create Date: 2023-03-28 23:22:29.143481

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '21b7c35b3419'
down_revision = '3e856b1ea0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    op.execute("UPDATE administrators SET is_superadmin='FALSE'")
    op.alter_column('administrators', 'is_superadmin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrators', 'is_superadmin')
    # ### end Alembic commands ###
