"""add superadmin field to admin

Revision ID: 78f2160b69cf
Revises: 3e856b1ea0c1
Create Date: 2023-03-24 12:48:08.011368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f2160b69cf'
down_revision = '3e856b1ea0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('superadmin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrators', 'superadmin')
    # ### end Alembic commands ###
