"""add is_superuser field to admin

Revision ID: bee6c3c24882
Revises: 3e856b1ea0c1
Create Date: 2023-03-28 23:06:47.148442

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bee6c3c24882'
down_revision = '3e856b1ea0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('is_superadmin', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrators', 'is_superadmin')
    # ### end Alembic commands ###
