"""changed reports_status_type

Revision ID: f4645f80c3ac
Revises: 73c0ad19dc7a
Create Date: 2023-02-02 10:47:37.635003

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4645f80c3ac'
down_revision = '73c0ad19dc7a'
branch_labels = None
depends_on = None

TABLE_NAME = "reports"
COLUMN_NAME = "status"
STATUSES = ("reviewing", "approved", "declined", "waiting")
NEW_STATUS_NAME = "report_status"
OLD_STATUS_NAME = "user_task_status"

REPORT_OLD_ENUM = sa.Enum(*STATUSES, name=OLD_STATUS_NAME)
REPORT_OLD_ENUM_PG = postgresql.ENUM(*STATUSES, name=OLD_STATUS_NAME)
REPORT_OLD_ENUM_VARIANT = REPORT_OLD_ENUM.with_variant(REPORT_OLD_ENUM_PG, "postgresql")
REPORT_NEW_ENUM = sa.Enum(*STATUSES, name=NEW_STATUS_NAME)
REPORT_NEW_ENUM_PG = postgresql.ENUM(*STATUSES, name=NEW_STATUS_NAME)
REPORT_NEW_ENUM_VARIANT = REPORT_NEW_ENUM.with_variant(REPORT_NEW_ENUM_PG, "postgresql")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    REPORT_NEW_ENUM_VARIANT.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        TABLE_NAME,
        COLUMN_NAME,
        existing_type=REPORT_OLD_ENUM_VARIANT,
        type_=REPORT_NEW_ENUM_VARIANT,
        postgresql_using=f"{COLUMN_NAME}::text::{NEW_STATUS_NAME}"
    )
    REPORT_OLD_ENUM_VARIANT.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    REPORT_OLD_ENUM_VARIANT.create(op.get_bind(), checkfirst=False)
    op.alter_column(
        TABLE_NAME,
        COLUMN_NAME,
        existing_type=REPORT_NEW_ENUM_VARIANT,
        type_=REPORT_OLD_ENUM_VARIANT,
        postgresql_using=f"{COLUMN_NAME}::text::{OLD_STATUS_NAME}"
    )
    REPORT_NEW_ENUM_VARIANT.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
