"""add root field to Administrator

Revision ID: 5103ca5f1df6
Revises: dc87d0573547
Create Date: 2023-03-21 13:55:10.744340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5103ca5f1df6'
down_revision = 'dc87d0573547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('root', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrators', 'root')
    # ### end Alembic commands ###
