"""changed reports_status_type

Revision ID: f4645f80c3ac
Revises: c58512d0c0c1
Create Date: 2023-01-31 21:41:37.635003

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4645f80c3ac'
down_revision = 'c58512d0c0c1'
branch_labels = None
depends_on = None

table_name = "reports"
column_name = "status"
statuses = ("reviewing", "approved", "declined", "waiting")
new_status_name = "report_status"
old_status_name = "user_task_status"

report_old_enum = sa.Enum(*statuses, name=old_status_name)
report_old_enum_pg = postgresql.ENUM(*statuses, name=old_status_name)
report_old_enum_variant = report_old_enum.with_variant(report_old_enum_pg, "postgresql")
report_new_enum = sa.Enum(*statuses, name=new_status_name)
report_new_enum_pg = postgresql.ENUM(*statuses, name=new_status_name)
report_new_enum_variant = report_new_enum.with_variant(report_new_enum_pg, "postgresql")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    report_new_enum_variant.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        table_name,
        column_name,
        existing_type=report_old_enum_variant,
        type_=report_new_enum_variant,
        postgresql_using=f"{column_name}::text::{new_status_name}"
    )
    report_old_enum_variant.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    report_old_enum_variant.create(op.get_bind(), checkfirst=False)
    op.alter_column(
        table_name,
        column_name,
        existing_type=report_new_enum_variant,
        type_=report_old_enum_variant,
        postgresql_using=f"{column_name}::text::{old_status_name}"
    )
    report_new_enum_variant.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
