"""Add_field_is_test_user_in_User_model

Revision ID: d237eef85461
Revises: 5a1ecb2d17c4
Create Date: 2023-05-27 09:58:26.804754

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd237eef85461'
down_revision = '5a1ecb2d17c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_test_user', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_test_user')
    # ### end Alembic commands ###
