"""added default tasks

Revision ID: a6d858f5a96e
Revises: 36ecaebc781b
Create Date: 2023-01-18 12:25:57.080431

"""
from alembic import op

from src.core.settings import settings

# revision identifiers, used by Alembic.
revision = 'a6d858f5a96e'
down_revision = '36ecaebc781b'
branch_labels = None
depends_on = None

TASKS = (
    {'image': 'change_the_bed_linen.jpg', 'description': 'Поменяй постельное бельё'},
    {'image': 'clean_the_table.jpg', 'description': 'Убери со стола'},
    {'image': 'clean_the_teeth.jpg', 'description': 'Почисти зубы'},
    {'image': 'clean_up_the_closet.jpg', 'description': 'Убери в шкафу'},
    {'image': 'clean_your_shoes.jpg', 'description': 'Почисти обувь'},
    {'image': 'clean.jpg', 'description': 'Уборка'},
    {'image': 'comb_your_head.jpg', 'description': 'Расчеши голову'},
    {'image': 'hang_up_the_laundry.jpg', 'description': 'Развесь бельё'},
    {'image': 'household_chores.jpg', 'description': 'Домашние дела'},
    {'image': 'made_the_bed.jpg', 'description': 'Застели кровать'},
    {'image': 'make_a_sandwich.jpg', 'description': 'Сделай бутерброд'},
    {'image': 'make_food.jpg', 'description': 'Приготовь еду'},
    {'image': 'put_the_dishes_in_their_places.jpg', 'description': 'Расставь посуду по местам'},
    {'image': 'set_the_table.jpg', 'description': 'Накрой на стол'},
    {'image': 'shopping.jpg', 'description': 'Делай покупки'},
    {'image': 'sleepwear.jpg', 'description': 'Одежда для сна'},
    {'image': 'sort_the_laundry.jpg', 'description': 'Расстортируй бельё'},
    {'image': 'stroke_it.jpg', 'description': 'Погладь'},
    {'image': 'sweep.jpg', 'description': 'Подмети'},
    {'image': 'take_out_the_trash.jpg', 'description': 'Вынеси мусор'},
    {'image': 'things_in_their_places.jpg', 'description': 'Вещи по местам'},
    {'image': 'vacuumed.jpg', 'description': 'Пропылесось'},
    {'image': 'wash_after_yourself.jpg', 'description': 'Смой за собой'},
    {'image': 'wash_it.jpg', 'description': 'Постирай'},
    {'image': 'wash_the_dishes.jpg', 'description': 'Помой посуду'},
    {'image': 'wash_the_floor.jpg', 'description': 'Помой пол'},
    {'image': 'wash_the_hands.jpg', 'description': 'Помой руки'},
    {'image': 'wash_the_head.jpg', 'description': 'Помой голову'},
    {'image': 'wash.jpg', 'description': 'Вымой'},
    {'image': 'water_the_flowers.jpg', 'description': 'Полей цветы'},
    {'image': 'wipe_the_dust.jpg', 'description': 'Вытри пыль'}
)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for task in TASKS:
        op.execute(
            "INSERT INTO "
            "tasks(id, url, description) "
            "VALUES "
            f"(gen_random_uuid(), '{settings.task_image_url}/{task['image']}', '{task['description']}')"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM tasks")
    # ### end Alembic commands ###
