"""user_add_field_telegram_blocked

Revision ID: 592c7fbd05ee
Revises: a6d858f5a96e
Create Date: 2023-01-19 21:12:26.128054

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '592c7fbd05ee'
down_revision = 'a6d858f5a96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_blocked', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET telegram_blocked = False")
    op.alter_column('users', 'telegram_blocked', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_blocked')
    # ### end Alembic commands ###
