"""added_default_tasks

Revision ID: 5a1ecb2d17c4
Revises: 2c304127881b
Create Date: 2023-05-03 01:54:02.703700

"""
import json
from urllib.parse import urljoin

from alembic import op
import sqlalchemy as sa

from src.core.settings import settings

# revision identifiers, used by Alembic.
revision = '5a1ecb2d17c4'
down_revision = '2c304127881b'
branch_labels = None
depends_on = None


def upgrade():
    with open('tasks.json', 'r', encoding='UTF-8') as file:
        for task in json.load(file):
            op.execute(
                "INSERT INTO "
                "tasks(id, url, title, is_archived) "
                "VALUES "
                f"(gen_random_uuid(), '{urljoin(settings.task_image_url, task['filename'])}', '{task['title']}', {sa.sql.expression.false()})"
            )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM tasks")
    # ### end Alembic commands ###
