"""add report reviewer info

Revision ID: 34994596b667
Revises: 3e856b1ea0c1
Create Date: 2023-03-27 23:38:34.966533

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34994596b667'
down_revision = '3e856b1ea0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('changed_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('reports', sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'reports', 'administrators', ['changed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'reviewed_at')
    op.drop_column('reports', 'changed_by')
    # ### end Alembic commands ###
