"""admin superamin -> is_superadmin

Revision ID: 2b97b51cf163
Revises: 78f2160b69cf
Create Date: 2023-03-27 13:53:51.061302

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2b97b51cf163'
down_revision = '78f2160b69cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('is_superadmin', sa.Boolean(), nullable=False))
    op.drop_column('administrators', 'superadmin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('superadmin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('administrators', 'is_superadmin')
    # ### end Alembic commands ###
