"""add report reviewer info

Revision ID: a0d25a5827fd
Revises: 7e2638eb39b5
Create Date: 2023-03-28 00:06:50.452547

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0d25a5827fd'
down_revision = '7e2638eb39b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('reports', sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'reports', 'administrators', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'reviewed_at')
    op.drop_column('reports', 'updated_by')
    # ### end Alembic commands ###
