"""add root field to administrator

Revision ID: 1631b2e714d8
Revises: 3e856b1ea0c1
Create Date: 2023-03-22 15:08:47.603148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1631b2e714d8'
down_revision = '3e856b1ea0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('root', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrators', 'root')
    # ### end Alembic commands ###
