"""add_report_reviewer_info

Revision ID: bcda11280d4d
Revises: 861c749e429b
Create Date: 2023-04-02 19:17:14.224771

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcda11280d4d'
down_revision = '861c749e429b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('reports', sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'reports', 'administrators', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'reviewed_at')
    op.drop_column('reports', 'updated_by')
    # ### end Alembic commands ###
