"""user_add_field_telegram_blocked

Revision ID: 73c0ad19dc7a
Revises: c58512d0c0c1
Create Date: 2023-01-25 12:07:03.075311

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '73c0ad19dc7a'
down_revision = 'c58512d0c0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_blocked', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET telegram_blocked = False")
    op.alter_column('users', 'telegram_blocked', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_blocked')
    # ### end Alembic commands ###
