"""add_report_reviewer_info

Revision ID: e7970dc8db9c
Revises: 3e856b1ea0c1
Create Date: 2023-03-24 16:13:35.520388

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7970dc8db9c'
down_revision = '3e856b1ea0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('administrator_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('reports', sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'reports', 'administrators', ['administrator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'reviewed_at')
    op.drop_column('reports', 'administrator_id')
    # ### end Alembic commands ###
